
// Insurance companies
export enum CarrierEnum {
   TRANS_AMERICA = 'TRANS_AMERICA',
   MUTUAL_OF_OMAHA = 'MUTUAL_OF_OMAHA',
   F_AND_G = 'F&G',
   AET0 = 'AET0',
   AMERICO = 'AMERICO',
   COREBRIDGE = 'COREBRIDGE',
   OTIOOL_LIFE = '0TIO0L_LIFE',
   AMERICAN_AMICABLE = 'AMERICAN_AMICABLE',
   GREAT_WESTERN = 'GREAT_WESTERN',
   FORESTER = 'FORESTER',
   PROSPERITY = 'PROSPERITY',
   ETHOS = 'ETHOS'
}