export enum UploadTypeEnum {
  AGENTS = 'AGENTS',
  POLICIES = 'POLICIES',
  LICENSES = 'LICENSES',
  CONTRACTING = 'CONTRACTING',
  CONTRACTING_PRODUCTS = 'CONTRACTING_PRODUCTS',
  COMPENSATIONS = 'COMPENSATIONS',
  BOOK_OF_BUSINESS = 'BOOK_OF_BUSINESS',
}
