export enum EmployeeProfileStatus {
  INITIALIZED = 'INITIALIZED',
  DRAFTED = 'DRAFTED',
  SUBMITTED = 'SUBMITTED',
  PUBLISHED = 'PUBLISHED',
  UNPUBLISHED = 'UNPUBLISHED',
  DISABLED = 'DISABLED',
}
